### ISSUE TITLE
Fallback to `editor` if `$EDITOR` is not set

### ISSUE THREAD

**Issue by jelhan** [rwjblue/release-it-lerna-changelog#34]
The code requires an `$EDITOR` environment variable if the editor that should be used is not set with `launchEditor` option: https://github.com/rwjblue/release-it-lerna-changelog/blob/ce26aeffd7861d9ae95bd47a8470a8fa2ff95c32/index.js#L80-L91

Debian-based systems have an `editor` command alias that points to the default editor. This is used by many tools. Actually I never faced the need to set `$EDITOR` before. Should consider using it as a fallback if `$EDITOR` is not set.

**Comment by rwjblue** [comment]
Ya sounds cool to me. I hadn't heard about that tool before, definitely happy to try to fallback to that.

Also, just to make sure you noticed, you can specify a string to use for the `launchEditor` setting to specify _whatever_ command you want.

**Comment by rwjblue** [comment]
@jelhan - I don't have `editor` on my system, do you happen to have a link to the  docs for that so I can figure out how I might be able to use it?

**Comment by jelhan** [comment]
@rwjblue I wasn't able to find any documentation for it. As far as I'm aware it only exists on Debian and Debian-based distributions like Ubuntu. Here is an example from my system (Ubuntu 19.10):

```
$ which editor
/usr/bin/editor

$ ls -l /usr/bin/editor
lrwxrwxrwx 1 root root 24 Sep  8  2018 /usr/bin/editor -> /etc/alternatives/editor

$ ls -l /etc/alternatives/editor
lrwxrwxrwx 1 root root 18 Apr 14 22:58 /etc/alternatives/editor -> /usr/bin/vim.basic
```

It's configured with `update-alternatives --config editor`.

**Comment by rwjblue** [comment]
What does `editor --help` output?  I'm trying to figure out how to detect it and how to actually use it...

**Comment by jelhan** [comment]
> What does `editor --help` output? I'm trying to figure out how to detect it and how to actually use it...

As `editor` is just a symlink `editor --help` will output the same as the program linked to for `--help` argument. To detect if a command exists you can use `which <command>` on unix. It returns a non-zero exit code if the command does not exist in path. Otherwise the location of the executable in `$PATH` is returned.

```js
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function commandExists(command) {
  try {
    await exec(`which ${command}`);

    return true;
  } catch (error) {
    return false;
  }
}

commandExists(process.argv[2])
  .then(console.log);
```

```
$ node exists.js ls
true

$ node exists.js editor
true

$ node exists.js foo
false
```

I'm not sure if `which` is also available on macOS.

**Comment by rwjblue** [comment]
Oh! I see, I'm sorry I didn't read your prior message closely enough (and missed that it was a symlink 🤦).

**Comment by rwjblue** [comment]
Released in https://github.com/rwjblue/release-it-lerna-changelog/releases/tag/v2.2.0
